---
# tasks file for Instala-Tools_Gatto
#
- name: Instalar herramientas
  package:
    name: "{{ item }}"
    state: present
  loop:
    - htop
    - script
    - tmux
    - tree
    - speedtest-cli
